name: OpWatch
main: OpWatch.OpWatch
version: 1.3.12
author: Callum Denison Smith
date: 2016/04/06
description: Checks many things in the game and console, reports them to an op irc channel
commands:
  opwatch:
    description: Command to manage Op Bot
    aliases: opbot
    permission: OpWatch.Admin
    usage: /OpWatch

permissions:
  OpWatch.Admin:
    description: Allows control of the Op IRC Bot
    default: op
    author: Callum Denison Smith