name: OpWatch
main: org.hopto.smither.opwatch.OpWatch
version: "1.4.1"
author: "Callum Denison Smith"
description: "Checks many things in the game and console, reports them to an op irc channel"
commands:
  opwatch:
    description: "Command to manage Op Bot"
    aliases: opbot
    permission: OpWatch.Admin
    usage: /OpWatch

permissions:
  OpWatch.Admin:
    description: "Allows control of the Op IRC Bot"
    default: op